server:
  servlet-path: /*
  port: 8080        # http://localhost:8080/jobs

spring:
  batch:
    job:
      enabled: false
  h2:
    console:
      enabled: true
      path: /h2-console            #http://localhost:8080/h2-console
quartz:
  job:
    jobName: helloWorldJob|helloJobWithXml
    cronExpression: 0/5 * * * * ?|0/11 * * * * ?